import "@/styles/style.scss";
import RecoilContextProvider from "@/lib/recoil/RecoilContextProvider";

export const metadata = {
  title: "dh",
  description: "Generated by create next app",
};
export default function RootLayout({ children }:{children:React.ReactNode}) {

  return (
    <html lang="ko">
      <body>
        <RecoilContextProvider>{children}</RecoilContextProvider>
      </body>
    </html>
  )
}
