import "@/app/scss/style.scss";
import RecoilContextProvider from "@/lib/RecoilContextProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {

  return (
    <html lang="ko">
      <body>
        <RecoilContextProvider>{children}</RecoilContextProvider>
      </body>
    </html>
  )
}
