import "@/app/scss/style.scss";
import RecoilContextProvider from "@/lib/RecoilContextProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
/* 유저 IP 이슈
    0. IP를 이용해 유저가 어느 나라에서 접속했는지 파악할 수 있음
    1. 그런데 IP는 client component에서는 가져와지지 않음
    2. 상태관리 도구인 recoil은 client component에서만 사용됨
    3. 그래서 IP는 쿠키에 저장함
*/

  return (
    <html lang="ko">
      <body>
        <RecoilContextProvider>{children}</RecoilContextProvider>
      </body>
    </html>
  )
}