import "@/app/scss/style.scss";
import Globalboard from "./(components)/globalboard";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        {children}
        <Globalboard />
      </body>
    </html>
  );
}
